#include "inst_system.h"
#include "inst_controlflow.h"
#include "inst_graphics2d.h"
#include "inst_graphics3d.h"
#include "inst_dialogue.h"
#include "inst_sound.h"
#include "inst_movie.h"
#include "inst_gamespecific.h"
#include "inst_misc.h"
#include "inst_sghd.h"

// clang-format off

// STEINS;GATE Steam (SGHD). Started as a copy of opcodetables_sgps3.h;
// slots differing from it are documented in
// tests/compat/fixtures/sgps3_known_gaps.json and pinned by
// tests/compat/test_opcode_table_audit.py.

namespace Impacto {

namespace Vm {

InstructionProc inline constexpr OpcodeTableSystem_SGHD[256] = {
    InstEnd,                  // 00 00
    InstCreateThread,         // 00 01
    InstKillThread,           // 00 02
    InstReset,                // 00 03
    InstScriptLoad,           // 00 04
    InstWait,                 // 00 05
    InstHalt,                 // 00 06
    InstJump,                 // 00 07
    InstJumpTable,            // 00 08
    InstGetLabelAdr,          // 00 09
    InstIf,                   // 00 0A
    InstCall,                 // 00 0B
    InstJumpFar,              // 00 0C
    InstCallFar,              // 00 0D
    InstReturn,               // 00 0E
    InstLoop,                 // 00 0F
    InstFlagOnJump,           // 00 10
    InstFlagOnWait,           // 00 11
    InstSetFlag,              // 00 12
    InstResetFlag,            // 00 13
    InstCopyFlag,             // 00 14
    InstKeyOnJump,            // 00 15
    InstKeyWait,              // 00 16
    InstKeyWaitTimer,         // 00 17
    InstMemberWrite,          // 00 18
    InstThreadControl,        // 00 19
    InstGetSelfPointer,       // 00 1A
    InstLoadJump,             // 00 1B
    InstVsync,                // 00 1C
    InstTest,                 // 00 1D
    InstThreadControlStore,   // 00 1E
    InstSwitch,               // 00 1F
    InstCase,                 // 00 20
    InstBGMplay,              // 00 21
    InstBGMstop,              // 00 22
    InstSEplay,               // 00 23
    InstSEstop,               // 00 24
    InstPadAct,               // 00 25
    InstSSEplay,              // 00 26
    InstSSEstop,              // 00 27
    InstCopyThreadWork,       // 00 28
    InstUPLmenuUI,            // 00 29
    InstSaveOld,              // 00 2A
    InstSaveIconLoad,         // 00 2B
    InstBGMflag,              // 00 2C
    InstUPLxTitle,            // 00 2D
    InstPresence,             // 00 2E
    InstSetAchievement,          // 00 2F
    InstSetPlayer,            // 00 30
    InstVoiceTableLoadMaybe,  // 00 31
    InstSetPadCustom,         // 00 32
    InstMwait,                // 00 33
    InstTerminate,            // 00 34
    InstByteArgStubSGHD,      // 00 35
    InstAchievementIcon,      // 00 36
    InstVoicePlay,            // 00 37
    InstVoiceStopNew,         // 00 38
    InstVoicePlayWait,        // 00 39
    InstBGMduelPlay,          // 00 3A
    InstSNDpause,             // 00 3B
    InstSEplayWait,           // 00 3C
    InstDebugPrint,           // 00 3D
    InstResetSoundAll,        // 00 3E
    InstSNDloadStop,          // 00 3F
    InstBGMstopWait,          // 00 40
    InstByteArgStubSGHD,      // 00 41
    InstSetX360SysMesPos,     // 00 42
    InstSystemMesSGHD,        // 00 43
    InstSystemMenu,           // 00 44
    InstGetNowTime,           // 00 45
    InstGetSystemStatus,      // 00 46
    InstReboot,               // 00 47
    InstReloadScript,         // 00 48
    InstReloadScriptMenu,     // 00 49
    InstDebugEditer,          // 00 4A
    InstStubSGHD,             // 00 4B
    InstUnk004CSGHD,          // 00 4C
    InstUnknownSGHD,          // 00 4D
    InstPadActEx,             // 00 4E
    InstDebugSetup,           // 00 4F
    InstUselessJumpSGHD,      // 00 50
    InstGlobalSystemMessage,  // 00 51
    InstNopSGHD,              // 00 52
    InstUseless0053SGHD,      // 00 53
    InstCallIfFlag,           // 00 54
    InstReturnIfFlag,         // 00 55
    InstCallFarIfFlag,        // 00 56
    InstReturnIfFlag,         // 00 57
    InstUnk0058SGHD,          // 00 58
    InstUnk0059SGHD,          // 00 59
    InstUnknownSGHD,          // 00 5A
    InstUnknownSGHD,          // 00 5B
    InstUnknownSGHD,          // 00 5C
    InstUnknownSGHD,          // 00 5D
    InstUnknownSGHD,          // 00 5E
    InstNopSGHD,              // 00 5F
    InstUnknownSGHD,          // 00 60
    InstUnknownSGHD,          // 00 61
    InstUnknownSGHD,          // 00 62
    InstUnknownSGHD,          // 00 63
    InstUnknownSGHD,          // 00 64
    InstUnknownSGHD,          // 00 65
    InstUnknownSGHD,          // 00 66
    InstUnknownSGHD,          // 00 67
    InstUnknownSGHD,          // 00 68
    InstUnknownSGHD,          // 00 69
    InstUnknownSGHD,          // 00 6A
    InstUnknownSGHD,          // 00 6B
    InstUnknownSGHD,          // 00 6C
    InstUnknownSGHD,          // 00 6D
    InstUnknownSGHD,          // 00 6E
    InstUnknownSGHD,          // 00 6F
    InstUnknownSGHD,          // 00 70
    InstUnknownSGHD,          // 00 71
    InstUnknownSGHD,          // 00 72
    InstUnknownSGHD,          // 00 73
    InstUnknownSGHD,          // 00 74
    InstUnknownSGHD,          // 00 75
    InstUnknownSGHD,          // 00 76
    InstUnknownSGHD,          // 00 77
    InstUnknownSGHD,          // 00 78
    InstUnknownSGHD,          // 00 79
    InstUnknownSGHD,          // 00 7A
    InstUnknownSGHD,          // 00 7B
    InstUnknownSGHD,          // 00 7C
    InstUnknownSGHD,          // 00 7D
    InstUnknownSGHD,          // 00 7E
    InstUnknownSGHD,          // 00 7F
    InstUnknownSGHD,          // 00 80
    InstUnknownSGHD,          // 00 81
    InstUnknownSGHD,          // 00 82
    InstUnknownSGHD,          // 00 83
    InstUnknownSGHD,          // 00 84
    InstUnknownSGHD,          // 00 85
    InstUnknownSGHD,          // 00 86
    InstUnknownSGHD,          // 00 87
    InstUnknownSGHD,          // 00 88
    InstUnknownSGHD,          // 00 89
    InstUnknownSGHD,          // 00 8A
    InstUnknownSGHD,          // 00 8B
    InstUnknownSGHD,          // 00 8C
    InstUnknownSGHD,          // 00 8D
    InstUnknownSGHD,          // 00 8E
    InstUnknownSGHD,          // 00 8F
    InstUnknownSGHD,          // 00 90
    InstUnknownSGHD,          // 00 91
    InstUnknownSGHD,          // 00 92
    InstUnknownSGHD,          // 00 93
    InstUnknownSGHD,          // 00 94
    InstUnknownSGHD,          // 00 95
    InstUnknownSGHD,          // 00 96
    InstUnknownSGHD,          // 00 97
    InstUnknownSGHD,          // 00 98
    InstUnknownSGHD,          // 00 99
    InstUnknownSGHD,          // 00 9A
    InstUnknownSGHD,          // 00 9B
    InstUnknownSGHD,          // 00 9C
    InstUnknownSGHD,          // 00 9D
    InstUnknownSGHD,          // 00 9E
    InstUnknownSGHD,          // 00 9F
    InstUnknownSGHD,          // 00 A0
    InstUnknownSGHD,          // 00 A1
    InstUnknownSGHD,          // 00 A2
    InstUnknownSGHD,          // 00 A3
    InstUnknownSGHD,          // 00 A4
    InstUnknownSGHD,          // 00 A5
    InstUnknownSGHD,          // 00 A6
    InstUnknownSGHD,          // 00 A7
    InstUnknownSGHD,          // 00 A8
    InstUnknownSGHD,          // 00 A9
    InstUnknownSGHD,          // 00 AA
    InstUnknownSGHD,          // 00 AB
    InstUnknownSGHD,          // 00 AC
    InstUnknownSGHD,          // 00 AD
    InstUnknownSGHD,          // 00 AE
    InstUnknownSGHD,          // 00 AF
    InstUnknownSGHD,          // 00 B0
    InstUnknownSGHD,          // 00 B1
    InstUnknownSGHD,          // 00 B2
    InstUnknownSGHD,          // 00 B3
    InstUnknownSGHD,          // 00 B4
    InstUnknownSGHD,          // 00 B5
    InstUnknownSGHD,          // 00 B6
    InstUnknownSGHD,          // 00 B7
    InstUnknownSGHD,          // 00 B8
    InstUnknownSGHD,          // 00 B9
    InstUnknownSGHD,          // 00 BA
    InstUnknownSGHD,          // 00 BB
    InstUnknownSGHD,          // 00 BC
    InstUnknownSGHD,          // 00 BD
    InstUnknownSGHD,          // 00 BE
    InstUnknownSGHD,          // 00 BF
    InstUnknownSGHD,          // 00 C0
    InstUnknownSGHD,          // 00 C1
    InstUnknownSGHD,          // 00 C2
    InstUnknownSGHD,          // 00 C3
    InstUnknownSGHD,          // 00 C4
    InstUnknownSGHD,          // 00 C5
    InstUnknownSGHD,          // 00 C6
    InstUnknownSGHD,          // 00 C7
    InstUnknownSGHD,          // 00 C8
    InstUnknownSGHD,          // 00 C9
    InstUnknownSGHD,          // 00 CA
    InstUnknownSGHD,          // 00 CB
    InstUnknownSGHD,          // 00 CC
    InstUnknownSGHD,          // 00 CD
    InstUnknownSGHD,          // 00 CE
    InstUnknownSGHD,          // 00 CF
    InstUnknownSGHD,          // 00 D0
    InstUnknownSGHD,          // 00 D1
    InstUnknownSGHD,          // 00 D2
    InstUnknownSGHD,          // 00 D3
    InstUnknownSGHD,          // 00 D4
    InstUnknownSGHD,          // 00 D5
    InstUnknownSGHD,          // 00 D6
    InstUnknownSGHD,          // 00 D7
    InstUnknownSGHD,          // 00 D8
    InstUnknownSGHD,          // 00 D9
    InstUnknownSGHD,          // 00 DA
    InstUnknownSGHD,          // 00 DB
    InstUnknownSGHD,          // 00 DC
    InstUnknownSGHD,          // 00 DD
    InstUnknownSGHD,          // 00 DE
    InstUnknownSGHD,          // 00 DF
    InstUnknownSGHD,          // 00 E0
    InstUnknownSGHD,          // 00 E1
    InstUnknownSGHD,          // 00 E2
    InstUnknownSGHD,          // 00 E3
    InstUnknownSGHD,          // 00 E4
    InstUnknownSGHD,          // 00 E5
    InstUnknownSGHD,          // 00 E6
    InstUnknownSGHD,          // 00 E7
    InstUnknownSGHD,          // 00 E8
    InstUnknownSGHD,          // 00 E9
    InstUnknownSGHD,          // 00 EA
    InstUnknownSGHD,          // 00 EB
    InstUnknownSGHD,          // 00 EC
    InstUnknownSGHD,          // 00 ED
    InstUnknownSGHD,          // 00 EE
    InstUnknownSGHD,          // 00 EF
    InstUnknownSGHD,          // 00 F0
    InstUnknownSGHD,          // 00 F1
    InstUnknownSGHD,          // 00 F2
    InstUnknownSGHD,          // 00 F3
    InstUnknownSGHD,          // 00 F4
    InstUnknownSGHD,          // 00 F5
    InstUnknownSGHD,          // 00 F6
    InstUnknownSGHD,          // 00 F7
    InstUnknownSGHD,          // 00 F8
    InstUnknownSGHD,          // 00 F9
    InstUnknownSGHD,          // 00 FA
    InstUnknownSGHD,          // 00 FB
    InstUnknownSGHD,          // 00 FC
    InstUnknownSGHD,          // 00 FD
    InstUnknownSGHD,          // 00 FE
    InstUnknownSGHD           // 00 FF
};

InstructionProc inline constexpr OpcodeTableGraph_SGHD[256] = {
    InstCreateSurf,        // 01 00
    InstReleaseSurf,       // 01 01
    InstLoadPic,           // 01 02
    InstReleaseSurf,       // 01 03
    InstSurfFill,          // 01 04
    InstCalc,              // 01 05
    InstUnk0106SGHD,       // 01 06
    InstUnk0107SGHD,       // 01 07
    InstByteArgStubSGHD,   // 01 08
    InstCheckpointSGHD,    // 01 09
    InstByteArgStubSGHD,   // 01 0A
    InstMesVoiceWait,      // 01 0B
    InstMes,               // 01 0C
    InstMesMain,           // 01 0D
    InstSetMesModeFormat,  // 01 0E
    InstSetNGmoji,         // 01 0F
    InstMesRev,            // 01 10
    InstMessWindow,        // 01 11
    InstSel,               // 01 12
    InstSelect,            // 01 13
    InstSysSel,            // 01 14
    InstSysSelect,         // 01 15
    InstUnknownSGHD,       // 01 16
    InstUnknownSGHD,       // 01 17
    InstUnknownSGHD,       // 01 18
    InstUnknownSGHD,       // 01 19
    InstUnknownSGHD,       // 01 1A
    InstUnknownSGHD,       // 01 1B
    InstUnknownSGHD,       // 01 1C
    InstUnknownSGHD,       // 01 1D
    InstUnknownSGHD,       // 01 1E
    InstUnk011F,           // 01 1F
    InstSCcapture,         // 01 20
    InstSetTextTable,      // 01 21
    InstPlayMovie,         // 01 22
    InstMovieMain,         // 01 23
    InstLoadMovie,         // 01 24
    InstSetRevMes,         // 01 25
    InstPlayMovieMemory,   // 01 26
    InstPlayMovie,         // 01 27
    InstMovieMain,         // 01 28
    InstLoadMovie,         // 01 29
    InstPlayMovieMemory,   // 01 2A
    InstSFDpause,          // 01 2B
    InstPlayMovie,         // 01 2C
    InstUnk012D,           // 01 2D
    InstUnknownSGHD,       // 01 2E
    InstUnknownSGHD,       // 01 2F
    InstUnknownSGHD,       // 01 30
    InstUnknownSGHD,       // 01 31
    InstUnknownSGHD,       // 01 32
    InstUnknownSGHD,       // 01 33
    InstUnknownSGHD,       // 01 34
    InstUnknownSGHD,       // 01 35
    InstUnknownSGHD,       // 01 36
    InstUnknownSGHD,       // 01 37
    InstUnknownSGHD,       // 01 38
    InstUnknownSGHD,       // 01 39
    InstUnknownSGHD,       // 01 3A
    InstUnknownSGHD,       // 01 3B
    InstUnknownSGHD,       // 01 3C
    InstUnknownSGHD,       // 01 3D
    InstUnknownSGHD,       // 01 3E
    InstUnknownSGHD,       // 01 3F
    InstUnknownSGHD,       // 01 40
    InstUnknownSGHD,       // 01 41
    InstUnknownSGHD,       // 01 42
    InstUnknownSGHD,       // 01 43
    InstUnknownSGHD,       // 01 44
    InstUnknownSGHD,       // 01 45
    InstUnknownSGHD,       // 01 46
    InstUnknownSGHD,       // 01 47
    InstUnknownSGHD,       // 01 48
    InstUnknownSGHD,       // 01 49
    InstUnknownSGHD,       // 01 4A
    InstUnknownSGHD,       // 01 4B
    InstUnknownSGHD,       // 01 4C
    InstUnknownSGHD,       // 01 4D
    InstUnknownSGHD,       // 01 4E
    InstUnknownSGHD,       // 01 4F
    InstUnknownSGHD,       // 01 50
    InstUnknownSGHD,       // 01 51
    InstUnknownSGHD,       // 01 52
    InstUnknownSGHD,       // 01 53
    InstUnknownSGHD,       // 01 54
    InstUnknownSGHD,       // 01 55
    InstUnknownSGHD,       // 01 56
    InstUnknownSGHD,       // 01 57
    InstUnknownSGHD,       // 01 58
    InstUnknownSGHD,       // 01 59
    InstUnknownSGHD,       // 01 5A
    InstUnknownSGHD,       // 01 5B
    InstUnknownSGHD,       // 01 5C
    InstUnknownSGHD,       // 01 5D
    InstUnknownSGHD,       // 01 5E
    InstUnknownSGHD,       // 01 5F
    InstUnknownSGHD,       // 01 60
    InstUnknownSGHD,       // 01 61
    InstUnknownSGHD,       // 01 62
    InstUnknownSGHD,       // 01 63
    InstUnknownSGHD,       // 01 64
    InstUnknownSGHD,       // 01 65
    InstUnknownSGHD,       // 01 66
    InstUnknownSGHD,       // 01 67
    InstUnknownSGHD,       // 01 68
    InstUnknownSGHD,       // 01 69
    InstUnknownSGHD,       // 01 6A
    InstUnknownSGHD,       // 01 6B
    InstUnknownSGHD,       // 01 6C
    InstUnknownSGHD,       // 01 6D
    InstUnknownSGHD,       // 01 6E
    InstUnknownSGHD,       // 01 6F
    InstUnknownSGHD,       // 01 70
    InstUnknownSGHD,       // 01 71
    InstUnknownSGHD,       // 01 72
    InstUnknownSGHD,       // 01 73
    InstUnknownSGHD,       // 01 74
    InstUnknownSGHD,       // 01 75
    InstUnknownSGHD,       // 01 76
    InstUnknownSGHD,       // 01 77
    InstUnknownSGHD,       // 01 78
    InstUnknownSGHD,       // 01 79
    InstUnknownSGHD,       // 01 7A
    InstUnknownSGHD,       // 01 7B
    InstUnknownSGHD,       // 01 7C
    InstUnknownSGHD,       // 01 7D
    InstUnknownSGHD,       // 01 7E
    InstUnknownSGHD,       // 01 7F
    InstUnknownSGHD,       // 01 80
    InstUnknownSGHD,       // 01 81
    InstUnknownSGHD,       // 01 82
    InstUnknownSGHD,       // 01 83
    InstUnknownSGHD,       // 01 84
    InstUnknownSGHD,       // 01 85
    InstUnknownSGHD,       // 01 86
    InstUnknownSGHD,       // 01 87
    InstUnknownSGHD,       // 01 88
    InstUnknownSGHD,       // 01 89
    InstUnknownSGHD,       // 01 8A
    InstUnknownSGHD,       // 01 8B
    InstUnknownSGHD,       // 01 8C
    InstUnknownSGHD,       // 01 8D
    InstUnknownSGHD,       // 01 8E
    InstUnknownSGHD,       // 01 8F
    InstUnknownSGHD,       // 01 90
    InstUnknownSGHD,       // 01 91
    InstUnknownSGHD,       // 01 92
    InstUnknownSGHD,       // 01 93
    InstUnknownSGHD,       // 01 94
    InstUnknownSGHD,       // 01 95
    InstUnknownSGHD,       // 01 96
    InstUnknownSGHD,       // 01 97
    InstUnknownSGHD,       // 01 98
    InstUnknownSGHD,       // 01 99
    InstUnknownSGHD,       // 01 9A
    InstUnknownSGHD,       // 01 9B
    InstUnknownSGHD,       // 01 9C
    InstUnknownSGHD,       // 01 9D
    InstUnknownSGHD,       // 01 9E
    InstUnknownSGHD,       // 01 9F
    InstUnknownSGHD,       // 01 A0
    InstUnknownSGHD,       // 01 A1
    InstUnknownSGHD,       // 01 A2
    InstUnknownSGHD,       // 01 A3
    InstUnknownSGHD,       // 01 A4
    InstUnknownSGHD,       // 01 A5
    InstUnknownSGHD,       // 01 A6
    InstUnknownSGHD,       // 01 A7
    InstUnknownSGHD,       // 01 A8
    InstUnknownSGHD,       // 01 A9
    InstUnknownSGHD,       // 01 AA
    InstUnknownSGHD,       // 01 AB
    InstUnknownSGHD,       // 01 AC
    InstUnknownSGHD,       // 01 AD
    InstUnknownSGHD,       // 01 AE
    InstUnknownSGHD,       // 01 AF
    InstUnknownSGHD,       // 01 B0
    InstUnknownSGHD,       // 01 B1
    InstUnknownSGHD,       // 01 B2
    InstUnknownSGHD,       // 01 B3
    InstUnknownSGHD,       // 01 B4
    InstUnknownSGHD,       // 01 B5
    InstUnknownSGHD,       // 01 B6
    InstUnknownSGHD,       // 01 B7
    InstUnknownSGHD,       // 01 B8
    InstUnknownSGHD,       // 01 B9
    InstUnknownSGHD,       // 01 BA
    InstUnknownSGHD,       // 01 BB
    InstUnknownSGHD,       // 01 BC
    InstUnknownSGHD,       // 01 BD
    InstUnknownSGHD,       // 01 BE
    InstUnknownSGHD,       // 01 BF
    InstUnknownSGHD,       // 01 C0
    InstUnknownSGHD,       // 01 C1
    InstUnknownSGHD,       // 01 C2
    InstUnknownSGHD,       // 01 C3
    InstUnknownSGHD,       // 01 C4
    InstUnknownSGHD,       // 01 C5
    InstUnknownSGHD,       // 01 C6
    InstUnknownSGHD,       // 01 C7
    InstUnknownSGHD,       // 01 C8
    InstUnknownSGHD,       // 01 C9
    InstUnknownSGHD,       // 01 CA
    InstUnknownSGHD,       // 01 CB
    InstUnknownSGHD,       // 01 CC
    InstUnknownSGHD,       // 01 CD
    InstUnknownSGHD,       // 01 CE
    InstUnknownSGHD,       // 01 CF
    InstUnknownSGHD,       // 01 D0
    InstUnknownSGHD,       // 01 D1
    InstUnknownSGHD,       // 01 D2
    InstUnknownSGHD,       // 01 D3
    InstUnknownSGHD,       // 01 D4
    InstUnknownSGHD,       // 01 D5
    InstUnknownSGHD,       // 01 D6
    InstUnknownSGHD,       // 01 D7
    InstUnknownSGHD,       // 01 D8
    InstUnknownSGHD,       // 01 D9
    InstUnknownSGHD,       // 01 DA
    InstUnknownSGHD,       // 01 DB
    InstUnknownSGHD,       // 01 DC
    InstUnknownSGHD,       // 01 DD
    InstUnknownSGHD,       // 01 DE
    InstUnknownSGHD,       // 01 DF
    InstUnknownSGHD,       // 01 E0
    InstUnknownSGHD,       // 01 E1
    InstUnknownSGHD,       // 01 E2
    InstUnknownSGHD,       // 01 E3
    InstUnknownSGHD,       // 01 E4
    InstUnknownSGHD,       // 01 E5
    InstUnknownSGHD,       // 01 E6
    InstUnknownSGHD,       // 01 E7
    InstUnknownSGHD,       // 01 E8
    InstUnknownSGHD,       // 01 E9
    InstUnknownSGHD,       // 01 EA
    InstUnknownSGHD,       // 01 EB
    InstUnknownSGHD,       // 01 EC
    InstUnknownSGHD,       // 01 ED
    InstUnknownSGHD,       // 01 EE
    InstUnknownSGHD,       // 01 EF
    InstUnknownSGHD,       // 01 F0
    InstUnknownSGHD,       // 01 F1
    InstUnknownSGHD,       // 01 F2
    InstUnknownSGHD,       // 01 F3
    InstUnknownSGHD,       // 01 F4
    InstUnknownSGHD,       // 01 F5
    InstUnknownSGHD,       // 01 F6
    InstUnknownSGHD,       // 01 F7
    InstUnknownSGHD,       // 01 F8
    InstUnknownSGHD,       // 01 F9
    InstUnknownSGHD,       // 01 FA
    InstUnknownSGHD,       // 01 FB
    InstUnknownSGHD,       // 01 FC
    InstUnknownSGHD,       // 01 FD
    InstUnknownSGHD,       // 01 FE
    InstUnknownSGHD        // 01 FF
};

InstructionProc inline constexpr OpcodeTableUser1_SGHD[256] = {
    InstMSinit,            // 10 00
    InstBGload,            // 10 01
    InstBGswap,            // 10 02
    InstBGsetColor,        // 10 03
    InstBGsetLink,         // 10 04
    InstCHAload,           // 10 05
    InstCHAswap,           // 10 06
    InstBGcopy,            // 10 07
    InstCHAcopy,           // 10 08
    InstSaveSlot,          // 10 09
    InstSystemMain,        // 10 0A
    InstCharaLayerLoad,    // 10 0B
    InstGameInfoInit,      // 10 0C
    InstCHAmove,           // 10 0D
    InstBGloadEx,          // 10 0E
    InstUnknownSGHD,       // 10 0F
    InstBGrelease,         // 10 10
    InstCHArelease,        // 10 11
    InstNopSGHD,           // 10 12
    InstOption,            // 10 13
    InstSystemDataReset,   // 10 14
    InstDebugData,         // 10 15
    InstGetCharaPause,     // 10 16
    InstBGfadeExpInit,     // 10 17
    InstUnknownSGHD,       // 10 18
    InstUnknownSGHD,       // 10 19
    InstByteArgStubSGHD,   // 10 1A
    InstHelp,              // 10 1B
    InstAchievementMenu,   // 10 1C
    InstSoundMenu,         // 10 1D
    InstAllClear,          // 10 1E
    InstAlbum,             // 10 1F
    InstMovieMode,         // 10 20
    InstClistInit,         // 10 21
    InstAutoSave,          // 10 22
    InstSaveMenu,          // 10 23
    InstLoadData,          // 10 24
    InstUnknownSGHD,       // 10 25
    InstUnknownSGHD,       // 10 26
    InstEncyclopediaSGHD,  // 10 27
    InstSetPlayMode,       // 10 28
    InstSetEVflag,         // 10 29
    InstSetCutin,          // 10 2A
    InstUnknownSGHD,       // 10 2B
    InstUnknownSGHD,       // 10 2C
    InstAchChkTitle,       // 10 2D
    InstSetSceneViewFlag,  // 10 2E
    InstChkClearFlag,      // 10 2F
    InstBGeffectWave,      // 10 30
    InstGeotag,            // 10 31
    InstNameID,            // 10 32
    InstTips,              // 10 33
    InstTitleMenuOld,      // 10 34
    InstUnknownSGHD,       // 10 35
    InstBGeffect,          // 10 36
    InstPhoneSGHD,         // 10 37
    InstUnk1038Darling,    // 10 38
    InstTwipo,             // 10 39
    InstUnk103ASGHD,       // 10 3A
    InstUnknownSGHD,       // 10 3B
    InstUnknownSGHD,       // 10 3C
    InstUnknownSGHD,       // 10 3D
    InstUnknownSGHD,       // 10 3E
    InstByteArgStubSGHD,   // 10 3F
    InstNopSGHD,           // 10 40
    InstNopSGHD,           // 10 41
    InstUnknownSGHD,       // 10 42
    InstUnknownSGHD,       // 10 43
    InstUnknownSGHD,       // 10 44
    InstUnknownSGHD,       // 10 45
    InstUnknownSGHD,       // 10 46
    InstUnknownSGHD,       // 10 47
    InstUnknownSGHD,       // 10 48
    InstUnknownSGHD,       // 10 49
    InstUnknownSGHD,       // 10 4A
    InstUnknownSGHD,       // 10 4B
    InstUnknownSGHD,       // 10 4C
    InstUnknownSGHD,       // 10 4D
    InstUnknownSGHD,       // 10 4E
    InstUnknownSGHD,       // 10 4F
    InstUnknownSGHD,       // 10 50
    InstUnknownSGHD,       // 10 51
    InstUnknownSGHD,       // 10 52
    InstUnknownSGHD,       // 10 53
    InstUnknownSGHD,       // 10 54
    InstUnknownSGHD,       // 10 55
    InstUnknownSGHD,       // 10 56
    InstUnknownSGHD,       // 10 57
    InstUnknownSGHD,       // 10 58
    InstUnknownSGHD,       // 10 59
    InstUnknownSGHD,       // 10 5A
    InstUnknownSGHD,       // 10 5B
    InstUnknownSGHD,       // 10 5C
    InstUnknownSGHD,       // 10 5D
    InstUnknownSGHD,       // 10 5E
    InstUnknownSGHD,       // 10 5F
    InstUnknownSGHD,       // 10 60
    InstUnknownSGHD,       // 10 61
    InstUnknownSGHD,       // 10 62
    InstUnknownSGHD,       // 10 63
    InstUnknownSGHD,       // 10 64
    InstUnknownSGHD,       // 10 65
    InstUnknownSGHD,       // 10 66
    InstUnknownSGHD,       // 10 67
    InstUnknownSGHD,       // 10 68
    InstUnknownSGHD,       // 10 69
    InstUnknownSGHD,       // 10 6A
    InstUnknownSGHD,       // 10 6B
    InstUnknownSGHD,       // 10 6C
    InstUnknownSGHD,       // 10 6D
    InstUnknownSGHD,       // 10 6E
    InstUnknownSGHD,       // 10 6F
    InstUnknownSGHD,       // 10 70
    InstUnknownSGHD,       // 10 71
    InstUnknownSGHD,       // 10 72
    InstUnknownSGHD,       // 10 73
    InstUnknownSGHD,       // 10 74
    InstUnknownSGHD,       // 10 75
    InstUnknownSGHD,       // 10 76
    InstUnknownSGHD,       // 10 77
    InstUnknownSGHD,       // 10 78
    InstUnknownSGHD,       // 10 79
    InstUnknownSGHD,       // 10 7A
    InstUnknownSGHD,       // 10 7B
    InstUnknownSGHD,       // 10 7C
    InstUnknownSGHD,       // 10 7D
    InstUnknownSGHD,       // 10 7E
    InstUnknownSGHD,       // 10 7F
    InstUnknownSGHD,       // 10 80
    InstUnknownSGHD,       // 10 81
    InstUnknownSGHD,       // 10 82
    InstUnknownSGHD,       // 10 83
    InstUnknownSGHD,       // 10 84
    InstUnknownSGHD,       // 10 85
    InstUnknownSGHD,       // 10 86
    InstUnknownSGHD,       // 10 87
    InstUnknownSGHD,       // 10 88
    InstUnknownSGHD,       // 10 89
    InstUnknownSGHD,       // 10 8A
    InstUnknownSGHD,       // 10 8B
    InstUnknownSGHD,       // 10 8C
    InstUnknownSGHD,       // 10 8D
    InstUnknownSGHD,       // 10 8E
    InstUnknownSGHD,       // 10 8F
    InstUnknownSGHD,       // 10 90
    InstUnknownSGHD,       // 10 91
    InstUnknownSGHD,       // 10 92
    InstUnknownSGHD,       // 10 93
    InstUnknownSGHD,       // 10 94
    InstUnknownSGHD,       // 10 95
    InstUnknownSGHD,       // 10 96
    InstUnknownSGHD,       // 10 97
    InstUnknownSGHD,       // 10 98
    InstUnknownSGHD,       // 10 99
    InstUnknownSGHD,       // 10 9A
    InstUnknownSGHD,       // 10 9B
    InstUnknownSGHD,       // 10 9C
    InstUnknownSGHD,       // 10 9D
    InstUnknownSGHD,       // 10 9E
    InstUnknownSGHD,       // 10 9F
    InstUnknownSGHD,       // 10 A0
    InstUnknownSGHD,       // 10 A1
    InstUnknownSGHD,       // 10 A2
    InstUnknownSGHD,       // 10 A3
    InstUnknownSGHD,       // 10 A4
    InstUnknownSGHD,       // 10 A5
    InstUnknownSGHD,       // 10 A6
    InstUnknownSGHD,       // 10 A7
    InstUnknownSGHD,       // 10 A8
    InstUnknownSGHD,       // 10 A9
    InstUnknownSGHD,       // 10 AA
    InstUnknownSGHD,       // 10 AB
    InstUnknownSGHD,       // 10 AC
    InstUnknownSGHD,       // 10 AD
    InstUnknownSGHD,       // 10 AE
    InstUnknownSGHD,       // 10 AF
    InstUnknownSGHD,       // 10 B0
    InstUnknownSGHD,       // 10 B1
    InstUnknownSGHD,       // 10 B2
    InstUnknownSGHD,       // 10 B3
    InstUnknownSGHD,       // 10 B4
    InstUnknownSGHD,       // 10 B5
    InstUnknownSGHD,       // 10 B6
    InstUnknownSGHD,       // 10 B7
    InstUnknownSGHD,       // 10 B8
    InstUnknownSGHD,       // 10 B9
    InstUnknownSGHD,       // 10 BA
    InstUnknownSGHD,       // 10 BB
    InstUnknownSGHD,       // 10 BC
    InstUnknownSGHD,       // 10 BD
    InstUnknownSGHD,       // 10 BE
    InstUnknownSGHD,       // 10 BF
    InstUnknownSGHD,       // 10 C0
    InstUnknownSGHD,       // 10 C1
    InstUnknownSGHD,       // 10 C2
    InstUnknownSGHD,       // 10 C3
    InstUnknownSGHD,       // 10 C4
    InstUnknownSGHD,       // 10 C5
    InstUnknownSGHD,       // 10 C6
    InstUnknownSGHD,       // 10 C7
    InstUnknownSGHD,       // 10 C8
    InstUnknownSGHD,       // 10 C9
    InstUnknownSGHD,       // 10 CA
    InstUnknownSGHD,       // 10 CB
    InstUnknownSGHD,       // 10 CC
    InstUnknownSGHD,       // 10 CD
    InstUnknownSGHD,       // 10 CE
    InstUnknownSGHD,       // 10 CF
    InstUnknownSGHD,       // 10 D0
    InstUnknownSGHD,       // 10 D1
    InstUnknownSGHD,       // 10 D2
    InstUnknownSGHD,       // 10 D3
    InstUnknownSGHD,       // 10 D4
    InstUnknownSGHD,       // 10 D5
    InstUnknownSGHD,       // 10 D6
    InstUnknownSGHD,       // 10 D7
    InstUnknownSGHD,       // 10 D8
    InstUnknownSGHD,       // 10 D9
    InstUnknownSGHD,       // 10 DA
    InstUnknownSGHD,       // 10 DB
    InstUnknownSGHD,       // 10 DC
    InstUnknownSGHD,       // 10 DD
    InstUnknownSGHD,       // 10 DE
    InstUnknownSGHD,       // 10 DF
    InstUnknownSGHD,       // 10 E0
    InstUnknownSGHD,       // 10 E1
    InstUnknownSGHD,       // 10 E2
    InstUnknownSGHD,       // 10 E3
    InstUnknownSGHD,       // 10 E4
    InstUnknownSGHD,       // 10 E5
    InstUnknownSGHD,       // 10 E6
    InstUnknownSGHD,       // 10 E7
    InstUnknownSGHD,       // 10 E8
    InstUnknownSGHD,       // 10 E9
    InstUnknownSGHD,       // 10 EA
    InstUnknownSGHD,       // 10 EB
    InstUnknownSGHD,       // 10 EC
    InstUnknownSGHD,       // 10 ED
    InstUnknownSGHD,       // 10 EE
    InstUnknownSGHD,       // 10 EF
    InstUnknownSGHD,       // 10 F0
    InstUnknownSGHD,       // 10 F1
    InstUnknownSGHD,       // 10 F2
    InstUnknownSGHD,       // 10 F3
    InstUnknownSGHD,       // 10 F4
    InstUnknownSGHD,       // 10 F5
    InstUnknownSGHD,       // 10 F6
    InstUnknownSGHD,       // 10 F7
    InstUnknownSGHD,       // 10 F8
    InstUnknownSGHD,       // 10 F9
    InstUnknownSGHD,       // 10 FA
    InstUnknownSGHD,       // 10 FB
    InstUnknownSGHD,       // 10 FC
    InstUnknownSGHD,       // 10 FD
    InstUnknownSGHD,       // 10 FE
    InstUnknownSGHD        // 10 FF
};

}

}

// clang-format on