#!/usr/bin/env python3
"""Generate profiles/sghd/font.lua (grid + advance widths) for the Steam font.

The Steam FONT.PNG is a 64 x 46 grid of 48 x 48 px cells (3072 x 2208,
Thread 06 census). The executable's own width table has not been located
yet, so widths are derived from each cell's horizontal ink extent:

    advance = min(cell, left + right + 1)     (equal side bearings)

measured with the same threshold as tools/sghd_census.py. Empty cells get
the full cell width, except the cells listed in EMPTY_WIDTHS (spaces).
Values are in bitmap pixels of a 48 px cell (impacto scales them by
font size / cell width).

Input is either the private census report or the Steam install itself:

    python3 tools/gen_sghd_font_widths.py --census sghd-census.txt
    python tools\\gen_sghd_font_widths.py --install "C:\\...\\STEINS;GATE"

Preferred (Thread 07): the executable's own table, found by
`tools/sghd_inspect.py widths` (best candidate, correlation >= 0.9):

    python3 tools/gen_sghd_font_widths.py --exe-widths sghd-widths.txt

Game.exe holds one byte per glyph for the first 384 glyphs (rows 0-5) in
units of a 32-unit em; they are scaled to the 48 px cell (x 1.5). Glyphs
after the table use the full cell, as the game does.

Only numbers are written; neither input file is read by tests or CI.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "profiles" / "sghd" / "font.lua"
COLUMNS, ROWS, CELL = 64, 46, 48
# glyph id -> width for cells without ink (default: a full cell, as the PS3
# table gives glyph 0). 63 is U+3000, the space the English scripts use
# (PS3 table: 12/32 of a cell -> 18/48).
EMPTY_WIDTHS = {63: 18}


def widths_from_rows(rows: list[list[str]]) -> list[int]:
    """rows: per grid row, per cell 'left-right' or '.'."""
    if len(rows) != ROWS or any(len(r) != COLUMNS for r in rows):
        raise ValueError(f"expected {ROWS} rows of {COLUMNS} cells")
    out = []
    for gy, row in enumerate(rows):
        for gx, cell in enumerate(row):
            glyph = gy * COLUMNS + gx
            if cell == ".":
                out.append(EMPTY_WIDTHS.get(glyph, CELL))
            else:
                left, right = (int(v) for v in cell.split("-"))
                out.append(min(CELL, left + right + 1))
    return out


def rows_from_census(text: str) -> list[list[str]]:
    section = text.split(" FONT.PNG ", 1)[1]
    head = section.split("\n", 2)[1]
    m = re.search(r"grid (\d+) columns x (\d+) rows, cell (\d+)x", head)
    if not m or tuple(int(v) for v in m.groups()) != (COLUMNS, ROWS, CELL):
        raise ValueError(f"unexpected FONT.PNG grid line: {head.strip()}")
    rows = re.findall(r"^\s+row\s+\d+: (.*)$", section, re.M)[:ROWS]
    return [r.split() for r in rows]


def rows_from_install(root: Path) -> list[list[str]]:
    sys.path.insert(0, str(REPO / "tools"))
    import sghd_census as census  # noqa: E402

    system = root / "USRDIR" / "system.mpk"
    entry = next(e for e in census.mpk_entries(system) if e[1].upper() == "FONT.PNG")
    lines = census.font_ink(census.mpk_read(system, entry), COLUMNS)
    text = "  id 9 FONT.PNG PNG\n" + "\n".join(lines)
    return rows_from_census(" " + text)


EXE_EM = 32
MIN_CORRELATION = 0.9


def widths_from_exe_report(text: str) -> tuple[list[float], dict]:
    """Cell widths from `sghd_inspect.py widths` output, plus provenance."""
    head = re.search(r"^\s+([\d.]+) (0x[0-9a-f]+) 1 :", text, re.M)
    if not head or float(head.group(1)) < MIN_CORRELATION:
        raise ValueError("no element-size-1 candidate with correlation >= 0.9")
    best = text.split("## best candidate", 1)[1]
    if head.group(2) not in best.split("\n", 1)[0]:
        raise ValueError("best candidate is not the top-ranked table")
    values = [int(v) for v in re.findall(r"\d+", best.split("\n", 1)[1])]
    table = []
    for v in values:  # the table ends at the first value outside 1..em
        if not 1 <= v <= EXE_EM:
            break
        table.append(v)
    if len(table) % COLUMNS or not table:
        raise ValueError(f"width table length {len(table)} is not whole rows")
    scale = CELL / EXE_EM
    widths = [v * scale for v in table] + [float(CELL)] * (COLUMNS * ROWS - len(table))
    return widths, {"offset": head.group(2), "correlation": float(head.group(1)),
                    "count": len(table)}


def render(widths: list[float], source: str | None = None) -> str:
    body = []
    for gy in range(ROWS):
        chunk = widths[gy * COLUMNS:(gy + 1) * COLUMNS]
        for half in (chunk[:32], chunk[32:]):
            body.append("    " + ", ".join(f"{w:g}" for w in half) + ",")
    header = source or """-- GENERATED by tools/gen_sghd_font_widths.py from the Steam FONT.PNG
-- ink extents (owner census, Thread 06). Do not edit by hand.
-- FONT.PNG: 3072x2208, 64x46 cells of 48 px; widths in 48 px cell units,
-- advance = left + right + 1 (equal side bearings). APPROXIMATION until the
-- Game.exe width table is located (tools/sghd_inspect.py widths)."""
    return f"""{header}
root.Fonts = {{
    ["Default"] = {{
        Type = FontType.SingleSheet,
        Sheet = "Font",
        GridSize = {{ X = {COLUMNS}, Y = {ROWS} }},
        AdvanceWidthsTable = {{
{chr(10).join(body)}
        }},
    }}
}};
"""


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[0] not in ("--census", "--install", "--exe-widths"):
        print(__doc__, file=sys.stderr)
        return 2
    path = Path(argv[1])
    if argv[0] == "--exe-widths":
        raw = path.read_bytes()
        text = raw.decode("utf-16") if raw[:2] in (b"\xff\xfe", b"\xfe\xff") else raw.decode()
        widths, info = widths_from_exe_report(text.replace("\r", ""))
        source = (f"""-- GENERATED by tools/gen_sghd_font_widths.py from the Game.exe glyph
-- width table (owner report, Thread 07: file offset {info['offset']}, {info['count']} glyphs,
-- correlation {info['correlation']:.3f} with the FONT.PNG ink). Do not edit by hand.
-- FONT.PNG: 3072x2208, 64x46 cells of 48 px. Game.exe stores widths in a
-- 32-unit em; scaled x1.5 to the cell. Later glyphs use the full cell.""")
        OUT.write_text(render(widths, source), encoding="utf-8")
        print(f"wrote {OUT}")
        return 0
    if argv[0] == "--census":
        raw = path.read_bytes()
        text = raw.decode("utf-16") if raw[:2] in (b"\xff\xfe", b"\xfe\xff") else raw.decode()
        rows = rows_from_census(text.replace("\r", ""))
    else:
        rows = rows_from_install(path)
    OUT.write_text(render(widths_from_rows(rows)), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
