#!/usr/bin/env python3
"""Generate profiles/sghd/charset.lua from tools/data/sghd_charset.utf8.

The data file is CommitteeOfZero/sc3tools resources/sghd/charset.utf8 (MIT,
commit 2945fe1a65e9e69c9c39eabcf729fd3895c4998f): one character per glyph id,
2895 glyphs. impacto turns it into Charset.Flags and Charset.CharacterToSc3
at profile load via UpdateCharset() in profiles/common/charset.lua.

    python3 tools/gen_sghd_charset.py          # rewrite charset.lua
    python3 tools/gen_sghd_charset.py --check  # exit 1 if out of date
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "tools" / "data" / "sghd_charset.utf8"
OUT = REPO / "profiles" / "sghd" / "charset.lua"

SPACES = " \u3000"
# Same glyphs as the hand-written index lists in profiles/sgps3/charset.lua
WORD_ENDING = ("、。．，？！〜”ー）〕］｝〉》」』】☆★♪々"
               "ぁぃぅぇぉっゃゅょァィゥェォッャュョ–")
WORD_STARTING = "\u3000 “（〔［｛〈《「『【"


def lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    charset = DATA.read_text(encoding="utf-8")
    assert "\n" not in charset and len(charset) == 2895, len(charset)
    for ch in SPACES + WORD_ENDING + WORD_STARTING:
        assert ch in charset, ch
    return f"""-- GENERATED by tools/gen_sghd_charset.py from tools/data/sghd_charset.utf8
-- (CommitteeOfZero/sc3tools resources/sghd/charset.utf8, MIT). Do not edit.
-- Requires profiles/common/charset.lua (UpdateCharset, AddCharsetFlag).
-- Glyph ids are positions in CharsetStr (token 0x8000 + id). Unverified
-- against the Steam font sheet; see profiles/sghd/font.lua.

local charsetInternal = {{
    CharsetStr = {lua_string(charset)},
    Spaces = {lua_string(SPACES)},
    WordEndingPuncts = {lua_string(WORD_ENDING)},
}};

UpdateCharset(charsetInternal);

-- common/charset.lua only applies WordStartingPuncts when a field named
-- WordStartingPunct exists, so apply them explicitly.
AddCharsetFlag({lua_string(WORD_STARTING)}, charsetInternal.CharsetStr,
               CharacterTypeFlags.WordStartingPunct);
"""


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is out of date; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
